//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenDetalle
    {
        public int Id { get; set; }
        public int IdAlmacenMovimiento { get; set; }
        public int Idalmacen { get; set; }
        public decimal Cantidad { get; set; }
        public decimal costo { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual AlmacenMovimiento AlmacenMovimiento { get; set; }
    }
}
