//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenMovimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmacenMovimiento()
        {
            this.AlmacenDetalle = new HashSet<AlmacenDetalle>();
        }
    
        public int Id { get; set; }
        public int IdProveedor { get; set; }
        public int IdUsuarios { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public decimal Total { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenDetalle> AlmacenDetalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
