//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobantesImpuestos
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string ParteTexto { get; set; }
        public string ParteNumeros { get; set; }
        public string Observacionrd { get; set; }
    }
}
