//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionEmpresa
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public string Direccion { get; set; }
        public string Provincia { get; set; }
        public string Telefono { get; set; }
    }
}
