//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturacionDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdFacturacion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> ITBIS { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public string DescripcionImpuesto { get; set; }
    
        public virtual Facturacion Facturacion { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
