//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturacion()
        {
            this.CXC = new HashSet<CXC>();
            this.FacturacionDetalle = new HashSet<FacturacionDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idUsario { get; set; }
        public Nullable<int> IdTiPoDePago { get; set; }
        public Nullable<int> IdTipoDivisa { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Cerrada { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Cuadrada { get; set; }
        public Nullable<bool> Nula { get; set; }
        public string RazonNula { get; set; }
        public Nullable<bool> Contado { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<bool> pagada { get; set; }
        public string DetalleTipoDepago { get; set; }
        public Nullable<decimal> MontoRecibido { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXC> CXC { get; set; }
        public virtual TipoDeDivisa TipoDeDivisa { get; set; }
        public virtual TipoDePago TipoDePago { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturacionDetalle> FacturacionDetalle { get; set; }
    }
}
