//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompraDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdOrdenCompra { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
