//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.DataADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad
    {
        public int id { get; set; }
        public int IdUsuario { get; set; }
        public int IdModulo { get; set; }
        public Nullable<bool> Editar { get; set; }
        public Nullable<bool> Ver { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
